osx_image: xcode11.4
language: swift
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Communicator.xcworkspace -scheme Communicator_Tests -sdk iphonesimulator -destination 'OS=13.4.1,name=iPhone 8' | xcpretty
